version: "3"

services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    volumes:
      - ./minecraftdata:/data
      - ./plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      FORGEVERSION: "47.2.5"
      FORGE_INSTALLER_URL: https://github.com/ductin-dev/MinecraftConfig/blob/main/forge-1.20.1-47.2.5-installer.jar?raw=true
      ONLINE_MODE: "FALSE"
      MEMORY: "4G"
      VERSION: "1.20.1"
      OPS_FILE: "https://raw.githubusercontent.com/ductin-dev/MinecraftConfig/main/ops.json"
      ICON: "https://github.com/ductin-dev/MinecraftConfig/blob/main/icon.jpg?raw=true"
      OVERRIDE_ICON: "TRUE"
      OVERRIDE_OPS: "TRUE"
      # ENABLE_WHITELIST: "TRUE"
      # ENFORCE_WHITELIST: "TRUE"
      RESOURCE_PACK: http://link.com/to/pack.zip?=1
      RESOURCE_PACK_ENFORCE: TRUE
    tty: TRUE
    stdin_open: TRUE
volumes:
  minecraftdata:
    external: true
