version: "3"

services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    volumes:
      - ../minecraftdata:/data
      - ./plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Satdevelop Server"
      MOTD: "Duc Tin had gently flicked his finger to create this map, what Fsofters can not do"
      PVP: "FALSE"
      ONLINE_MODE: "FALSE"
      # ============================================
      MAX_PLAYERS: 5
      MEMORY: "4G"
      VERSION: "1.20.1"
      # ============================================
      # ENABLE_WHITELIST: "TRUE"
      # ENFORCE_WHITELIST: "TRUE"
      OVERRIDE_ICON: "TRUE"
      OVERRIDE_OPS: "TRUE"
      OPS_FILE: "https://raw.githubusercontent.com/ductin-dev/MinecraftConfig/main/ops.json"
      ICON: "https://github.com/ductin-dev/MinecraftConfig/blob/main/icon.jpg?raw=true"
      # ============================================
      FORGEVERSION: "47.0.45"
      FORGE_INSTALLER_URL: https://github.com/ductin-dev/MinecraftConfig/blob/main/forge-1.20.1-47.0.45-installer.jar?raw=true
      COPY_MODS_DEST: ./mods

      # ============================================
      # RESOURCE_PACK: https://github.com/ductin-dev/MinecraftConfig/blob/main/resourcepacks/Luna64x_1.20_Freepack.zip
      # RESOURCE_PACK_ENFORCE: TRUE
      # ============================================
      RCON_CMDS_STARTUP:  |-
        gamerule keepInventory true
        pregen start 200
    tty: TRUE
    stdin_open: TRUE
volumes:
  minecraftdata:
    external: true
